apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysqlcontainer
        image: mysql:8.3
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: kv-wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: kv-wordpress
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: "/mnt/"
            name: mysqlvolume   
      volumes:
      - name: mysqlvolume
        persistentVolumeClaim:
          claimName: pvcmysql     
      - name: akv-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "my-akv-class"
