apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentwp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpresscontainer
        image: wordpress:6.4.3-apache
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
        env:
        - name: WORDPRESS_DB_HOST
          value: servicio-mysql
        - name: WORDPRESS_DB_PASSWORD  
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: kv-wordpress
        - name: WORDPRESS_DB_USER
          value: wordpress
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html"
            name: wordpressvolume   
      volumes:
      - name: wordpressvolume
        persistentVolumeClaim:
          claimName: pvcwordpress     
