apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-akv-class
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "44b41934-ba7a-4cba-a835-647ffa65f2ad"   # Set the clientID of the user-assigned managed identity to use (ObjectID)
    keyvaultName: aks-kv83        # Set to the name of your key vault
    
    objects:  |
      array:
        - |
          objectName: kv-wordpress
          objectType: secret              # object types: secret, key, or cert
    tenantId: ce879769-c0c6-4264-b290-fe54a85c71af
  secretObjects:                             
  - secretName: dbsecrets   
    data:
    - key: kv-wordpress                          
      objectName: kv-wordpress                                        
    type: Opaque   
