apiVersion: v1
kind: Service
metadata:
  name: servicio-wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  clusterIP: None